projects:
  almostcms:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: w7hv2qd5nfdrtany6yayry3siu
      endpoints:
        prod: >-
          https://6jjrpl7fbjfgnk2zfqtp4s6ae4.appsync-api.us-east-1.amazonaws.com/graphql
